### ISSUE TITLE
Move frontend settings to production and develop settings file

### ISSUE THREAD

**Issue by hersonls** [hersonls/frango#3]
The main idea is avoid use if statements to set configurations in one only settings.py file. Now for better and easy configuration, we need move to a new structure:

```
settings/
  __init__.py
  base.py
  production.py
  develop.py
```

**Comment by mattjegan** [comment]
I submitted a PR for this #4 not sure if it's exactly what you had in mind though with frontend settings.

**Comment by hersonls** [comment]
@mattjegan yes, almost that, we need move this settings to production and develop settings:

https://github.com/hersonls/frango/blob/master/backend/backend/settings.py#L70
https://github.com/hersonls/frango/blob/master/backend/backend/settings.py#L117-L122

This is the variable that changes in two files:

https://github.com/hersonls/frango/blob/master/backend/backend/settings.py#L24
