### ISSUE TITLE
Failed to run make config

### ISSUE THREAD

**Issue by Bokerdev** [hersonls/frango#5]
Heloo Herson, I thanks for your Job that's split Back and Front and it's very helpful. But I got failed when run "make config" on my Ubuntu terminal. Below my npm-debug.log files:

[npm-debug.txt](https://github.com/hersonls/frango/files/719171/npm-debug.txt)

Get: error node-sass@3.13.1 postinstall: `node scripts/build.js`

Try to remove node modules and install npm

$ rm -rf node_modules
and
$ npm install

and the result always same like above.

**Comment by hersonls** [comment]
Hey @Bokerdev sorry the delay, the huge delay. I'm back to project and few month ago I did a lot of changes and we aren't using npm anymore, now is Yarn. Probably you have some dependencies problem with you OS. Try again with the new features and come back if you have the same problem again.

Thanks
