### ISSUE TITLE
Replace hard coded path in html for django static template tag

### ISSUE THREAD

**Issue by hersonls** [hersonls/frango#8]
In some cases we need to add Django the {% static %} template tag to get a URL for static files based in some types of storages. For example Amazon s3 with their custom url. To avoid hard coded path in distribution HTML need to be added in a replace method to replace all these urls and add to {% static %} tag.

**Comment by AlexChum** [comment]
I have pushed and requested a pull. Let me know if it was done right!
It's my first commit!

**Comment by hersonls** [comment]
Resolved by @marcodieba in PR #11
